#   encoding: utf-8
ch1V = [{'word':'um', 'romaji':'ano', 'kana':u'あの', 'hiragana':u'あの'},
        {'word':'now', 'romaji':'ima', 'kana':u'今', 'hiragana':u'いま'},
        {'word':'english', 'romaji':'eigo', 'kana':u'英語', 'hiragana':u'えいご'},
        {'word':'yes', 'romaji':['hai', 'ee'], 'kana':[u'はい', u'ええ'], 'hiragana':[u'はい', u'ええ']},
        {'word':'student', 'romaji':'gakusei', 'kana':u'学生', 'hiragana':u'がくせい'},
        {'word':'~language', 'romaji':'~go', 'kana':u'～語', 'hiragana':u'ご'},
        {'word':'high school', 'romaji':'koukou', 'kana':u'高校', 'hiragana':u'こうこう'},
        {'word':'p.m.', 'romaji':'gogo', 'kana':u'午後', 'hiragana':u'ごご'},
        {'word':'a.m.', 'romaji':'gozen', 'kana':u'午前', 'hiragana':u'ごぜん'},
        {'word':'~years old', 'romaji':'~sai', 'kana':u'～歳', 'hiragana':u'～さい'},
        {'word':['mr', 'mrs'], 'romaji':'~san', 'kana':u'～さん', 'hiragana':u'～さん'},
        {'word':'~o\'clock', 'romaji':'~ji', 'kana':u'～時', 'hiragana':u'～じ'},
        {'word':'~people', 'romaji':'~jin', 'kana':u'～人', 'hiragana':u'～じん'},
        {'word':'major', 'romaji':'senkou', 'kana':u'専攻', 'hiragana':u'せんこう'},
        {'word':['teacher', 'professor'], 'romaji':'sensei', 'kana':u'先生', 'hiragana':u'せんせい'},
        {'word':'that\'s right', 'romaji':'sou desu', 'kana':u'そうです', 'hiragana':u'そうです'},
        {'word':['I see', 'is that so?'], 'romaji':'sou desu ka', 'kana':u'そうですか', 'hiragana':u'そうですか'},
        {'word':['college', 'university'], 'romaji':'daigaku', 'kana':u'大学', 'hiragana':u'だいがく'},
        {'word':'telephone', 'romaji':'denwa', 'kana':u'電話', 'hiragana':u'でんわ'},
        {'word':'friend', 'romaji':'tomodachi', 'kana':u'友達', 'hiragana':u'ともだち'},
        {'word':'name', 'romaji':'namae', 'kana':u'名前', 'hiragana':u'なまえ'},
        {'word':'what', 'romaji':['nan', 'nani'], 'kana':u'何', 'hiragana':[u'なん', u'なに']},
        {'word':'japan', 'romaji':'nihon', 'kana':u'日本', 'hiragana':u'にほん'},
        {'word':'~year student', 'romaji':'~nensei', 'kana':u'～年生', 'hiragana':u'ねんせい'},
        {'word':'half past~', 'romaji':'~han', 'kana':u'～半', 'hiragana':u'～はん'},
        {'word':'number', 'romaji':'bangou', 'kana':u'番号', 'hiragana':u'ばんごう'},
        {'word':'international student', 'romaji':'ryuugakusei', 'kana':u'留学生', 'hiragana':u'りゅうがくせい'},
        {'word':'I', 'romaji':'watashi', 'kana':u'私', 'hiragana':u'わたし'},
        {'word':'usa', 'romaji':'amerika', 'kana':u'アメリカ', 'hiragana':u'アメリカ'},
        {'word':'britain', 'romaji':'igirisu', 'kana':u'イギリス', 'hiragana':u'イギリス'},
        {'word':'australia', 'romaji':'oosutoraria', 'kana':u'オーストラリア', 'hiragana':u'オーストラリア'},
        {'word':'korea', 'romaji':'kankoku', 'kana':u'韓国', 'hiragana':u'かんこく'},
        {'word':'sweden', 'romaji':'suweeden', 'kana':u'スウェーデン', 'hiragana':u'スウェーデン'},
        {'word':'china', 'romaji':'chuugoku', 'kana':u'中国', 'hiragana':u'ちゅうごく'},
        {'word':'science', 'romaji':'kagaku', 'kana':u'科学', 'hiragana':u'かがく'},
        {'word':'asian studies', 'romaji':'ajia kenkyuu', 'kana':u'アジア研究', 'hiragana':u'アジアけんきゅう'},
        {'word':'economics', 'romaji':'keizai', 'kana':u'経済', 'hiragana':u'けいざい'},
        {'word':'international relations', 'romaji':'kokusaikankei', 'kana':u'国際関係', 'hiragana':u'こくさいかんけい'},
        {'word':'computer', 'romaji':'konpyuutaa', 'kana':u'コンピュータ', 'hiragana':u'コンピュータ'},
        {'word':'anthropology', 'romaji':'jinruigaku', 'kana':u'人類学', 'hiragana':u'じんるいがく'},
        {'word':'politics', 'romaji':'seiji', 'kana':u'政治', 'hiragana':u'せいじ'},
        {'word':'business', 'romaji':'bijinesu', 'kana':u'ビジネス', 'hiragana':u'ビジネス'},
        {'word':'literature', 'romaji':'bungaku', 'kana':u'文学', 'hiragana':u'ぶんがく'},
        {'word':'history', 'romaji':'rekishi', 'kana':u'歴史', 'hiragana':u'れきし'},
        {'word':['job', 'work', 'occupation'], 'romaji':'shigoto', 'kana':u'仕事', 'hiragana':u'しごと'},
        {'word':'doctor', 'romaji':'isha', 'kana':u'医者', 'hiragana':u'いしゃ'},
        {'word':['office worker', 'worker'], 'romaji':'kaishain', 'kana':u'会社員', 'hiragana':u'かいしゃいん'},
        {'word':'high school student', 'romaji':'koukousei', 'kana':u'高校生', 'hiragana':u'こうこうせい'},
        {'word':'housewife', 'romaji':'shufu', 'kana':u'主婦', 'hiragana':u'しゅふ'},
        {'word':'graduate student', 'romaji':'daigakuinsei', 'kana':u'大学院生', 'hiragana':u'だいがくいんせい'},
        {'word':'college student', 'romaji':'daigakusei', 'kana':u'大学生', 'hiragana':u'だいがくせい'},
        {'word':'lawyer', 'romaji':'bengoshi', 'kana':u'弁護士', 'hiragana':u'べんごし'},
        {'word':'mother', 'romaji':'okaasan', 'kana':u'お母さん', 'hiragana':u'おかあさん'},
        {'word':'father', 'romaji':'otousan', 'kana':u'お父さん', 'hiragana':u'おとうさん'},
        {'word':'older sister', 'romaji':'oneesan', 'kana':u'お姉さん', 'hiragana':u'おねえさん'},
        {'word':'older brother', 'romaji':'oniisan', 'kana':u'お兄さん', 'hiragana':u'おにいさん'},
        {'word':'younger sister', 'romaji':'imouto', 'kana':u'妹', 'hiragana':u'いもうと'},
        {'word':'younger brother', 'romaji':'otouto', 'kana':u'弟', 'hiragana':u'おとうと'}]
