#   encoding: utf-8
ch2V = [{'word':['this','this one'] 'romaji':'kore', 'kana':u'これ', 'hiragana':u'これ'},
        {'word':['that', 'that one'], 'romaji':'sore', 'kana':u'それ', 'hiragana':u'それ'},
        {'word':['that (over there)', 'that one (over there)'], 'romaji':'are', 'kana':u'あれ', 'hiragana':u'あれ'},
        {'word':'which', 'romaji':'dore', 'kana':u'どれ', 'hiragana':u'どれ'},
        {'word':'this~', 'romaji':'kono~', 'kana':u'この～', 'hiragana':u'この～'},
        {'word':'that~', 'romaji':'sono~', 'kana':u'その～', 'hiragana':u'その～'},
        {'word':'that~ (over there)', 'romaji':'ano~', 'kana':u'あの～', 'hiragana':u'あの～'},
        {'word':'which~', 'romaji':'dono~', 'kana':u'どの～', 'hiragana':u'どの～'},
        {'word':'here', 'romaji':'koko', 'kana':u'ここ', 'hiragana':u'ここ'},
        {'word':'there', 'romaji':'soko', 'kana':u'そこ', 'hiragana':u'そこ'},
        {'word':'over there', 'romaji':'asoko', 'kana':u'あそこ', 'hiragana':u'あそこ'},
        {'word':'where', 'romaji':'doko', 'kana':u'どこ', 'hiragana':u'どこ'},
        {'word':'who', 'romaji':'dare', 'kana':u'だれ', 'hiragana':u'だれ'},
        {'word':'delicious', 'romaji':'oishii', 'kana':u'美味しい', 'hiragana':u'おいしい'},
        {'word':'fish', 'romaji':'sakana', 'kana':u'魚', 'hiragana':u'さかな'},
        {'word':'pork cutlet', 'romaji':'tonkatsu', 'kana':u'とんかつ', 'hiragana':u'とんかつ'},　
        {'word':'meat', 'romaji':'niku', 'kana':u'肉', 'hiragana':u'にく'},
        {'word':'menu', 'romaji':'menu', 'kana':u'メニュー', 'hiragana':u'メニュー'},
        {'word':'vegetable', 'romaji':'yasai', 'kana':u'野菜', 'hiragana':u'やさい'},
        {'word':'pencil', 'romaji':'enpitsu', 'kana':u'鉛筆', 'hiragana':u'えんぴつ'},
        {'word':'umbrella', 'romaji':'kasa', 'kana':u'傘', 'hiragana':u'かさ'},
        {'word':['bag','purse'], 'romaji':'kaban', 'kana':u'かばん', 'hiragana':u'かばん'},
        {'word':'shoes', 'romaji':'kutsu', 'kana':u'靴', 'hiragana':u'くつ'},
        {'word':'wallet', 'romaji':'saifu', 'kana':u'財布', 'hiragana':u'さいふ'},
        {'word':'jeans', 'romaji':'jiinzu', 'kana':u'ジーンズ', 'hiragana':u'ジーンズ'},
        {'word':'dictionary', 'romaji':'jisho', 'kana':u'辞書', 'hiragana':u'じしょ'},
        {'word':'bicycle', 'romaji':'jitensha', 'kana':u'自転車', 'hiragana':u'じてんしゃ'},
        {'word':'newspaper', 'romaji':'shinbun', 'kana':u'新聞', 'hiragana':u'しんぶん'},
        {'word':'t-shirt', 'romaji':'tiishatsu', 'kana':u'ｔシャツ', 'hiragana':u'ｔシャツ'},
        {'word':['watch', 'clock'], 'romaji':'tokei', 'kana':u'時計', 'hiragana':u'とけい'},
        {'word':'notebook', 'romaji':'nooto', 'kana':u'ノート', 'hiragana':u'ノート'},
        {'word':'pen', 'romaji':'pen', 'kana':u'ペン', 'hiragana':u'ペン'},
        {'word':['hat','cap'], 'romaji':'boushi', 'kana':u'帽子', 'hiragana':u'ぼうし'},
        {'word':'book', 'romaji':'hon', 'kana':u'本', 'hiragana':u'ほん'},
        {'word':'cafe', 'romaji':'kissaten', 'kana':u'喫茶店', 'hiragana':u'きっさてん'},
        {'word':'bank', 'romaji':'ginkou', 'kana':u'銀行', 'hiragana':u'ぎんこう'},
        {'word':['toilet','restroom'], 'romaji':'toire', 'kana':u'トイレ', 'hiragana':u'トイレ'},
        {'word':'library', 'romaji':'toshokan', 'kana':u'図書館', 'hiragana':u'としょかん'},
        {'word':'post office', 'romaji':'yuubinkyoku', 'kana':u'郵便局', 'hiragana':u'ゆうびんきょく'},
        {'word':'usa', 'romaji':'amerika', 'kana':u'アメリカ', 'hiragana':u'アメリカ'},
        {'word':'britain', 'romaji':'igirisu', 'kana':u'イギリス', 'hiragana':u'イギリス'},
        {'word':'korea', 'romaji':'kankoku', 'kana':u'韓国', 'hiragana':u'かんこく'},
        {'word':'china', 'romaji':'chuugoku', 'kana':u'中国', 'hiragana':u'ちゅうごく'},
        {'word':'economics', 'romaji':'keizai', 'kana':u'経済', 'hiragana':u'けいざい'},
        {'word':'computer', 'romaji':'konpyuutaa', 'kana':u'コンピューター', 'hiragana':u'コンピューター'},
        {'word':'business', 'romaji':'bijinesu', 'kana':u'ビジネス', 'hiragana':u'ビジネス'},
        {'word':'history', 'romaji':'rekishi', 'kana':u'歴史', 'hiragana':u'れきし'},
        {'word':'mother', 'romaji':'okaasan', 'kana':u'お母さん', 'hiragana':u'おかあさん'},
        {'word':'father', 'romaji':'otousan', 'kana':u'お父さん', 'hiragana':u'おとうさん'},
        {'word':'how much', 'romaji':'ikura', 'kana':u'いくら', 'hiragana':u'いくら'},
        {'word':'~yen', 'romaji':'~en', 'kana':u'～円', 'hiragana':u'～えん'},
        {'word':['high', 'expensive'], 'romaji':'takai', 'kana':u'高い', 'hiragana':u'たかい'},
        {'word':'welcome (to our store)', 'romaji':'irasshaimase', 'kana':u'いらっしゃいませ', 'hiragana':u'いらっしゃいませ'},
        {'word':'~,please', 'romaji':'~, onegaishimasu', 'kana':u'～、おねがいします', 'hiragana':u'～、おねがいします'},
        {'word':'please give me~', 'romaji':'~, kudasai', 'kana':u'～、ください', 'hiragana':u'～、ください'},
        {'word':['then~','if that is the case,~','well,~'], 'romaji':'jaa', 'kana':u'じゃあ～', 'hiragana':u'じゃあ～'},
        {'word':['please','here it is'], 'romaji':'douzo', 'kana':u'どうぞ', 'hiragana':u'どうぞ'},
        {'word':'thank you', 'romaji':'doumo', 'kana':u'どうも', 'hiragana':u'どうも'}]
