# encoding: utf-8
#These are only the gray highlighted ones
#char combinations that end with a small tsu are - in romaji
#template  {'kanji':u'', 'eng':'', 'romajip':'', 'hiraganap':u'', 'words':[{'word':'', 'kanji':u'', 'hiragana':u'', 'romaji':''},{'word':'', 'kanji':u'', 'hiragana':u'', 'romaji':''}]},
ch3K =[{'kanji':u'一', 'eng':'one', 'romajip':'ichi', 'hiraganap':u'いち',
            'words':[{'word':'one', 'kanji':u'一', 'hiragana':u'いち', 'romaji':'ichi'},{'word':'one o\'clock', 'kanji':u'一時', 'hiragana':u'いちじ', 'romaji':'ichiji'}]},
       {'kanji':u'二', 'eng':'two', 'romajip':'ni', 'hiraganap':u'に',
            'words':[{'word':'two', 'kanji':u'二', 'hiragana':u'に', 'romaji':'ni'},{'word':'two o\'clock', 'kanji':u'二時', 'hiragana':u'にじ', 'romaji':'niji'}]},
       {'kanji':u'三', 'eng':'three', 'romajip':'san', 'hiraganap':u'さん',
            'words':[{'word':'three', 'kanji':u'三', 'hiragana':u'さん', 'romaji':'san'},{'word':'three o\'clock', 'kanji':u'三時', 'hiragana':u'さんじ', 'romaji':'sanji'}]},
       {'kanji':u'四', 'eng':'four', 'romajip':['yon','yo'], 'hiraganap':[u'よん',u'よ'],
            'words':[{'word':'four', 'kanji':u'四', 'hiragana':u'よん', 'romaji':'yon'},{'word':'four o\'clock', 'kanji':u'四時', 'hiragana':u'よんじ', 'romaji':'yonji'}]},
       {'kanji':u'五', 'eng':'five', 'romajip':'go', 'hiraganap':u'ご',
            'words':[{'word':'five', 'kanji':u'五', 'hiragana':u'ご', 'romaji':'go'},{'word':'five o\'clock', 'kanji':u'五時', 'hiragana':u'ごじ', 'romaji':'goji'}]},
       {'kanji':u'六', 'eng':'six', 'romajip':['roku','ro-'], 'hiraganap':[u'ろく',u'ろっ'],
            'words':[{'word':'six', 'kanji':u'六', 'hiragana':u'ろく', 'romaji':'roku'},{'word':'six o\'clock', 'kanji':u'六時', 'hiragana':u'ろくじ', 'romaji':'rokuji'},
                    {'word':'six hundred', 'kanji':u'六百', 'hiragana':u'ろっぴゃく', 'romaji':'ropphyaku'}]},
       {'kanji':u'七', 'eng':'seven', 'romajip':['shichi','nana'], 'hiraganap':[u'しち',u'なな'],
            'words':[{'word':'seven', 'kanji':u'七', 'hiragana':[u'しち',u'なな'], 'romaji':['shichi','nana']},
                    {'word':'seven o\'clock', 'kanji':u'七時', 'hiragana':u'しちじ', 'romaji':'shichiji'}]},
       {'kanji':u'八', 'eng':'eight', 'romajip':['hachi','ha-'], 'hiraganap':[u'はち',u'はっ'],
            'words':[{'word':'eight', 'kanji':u'八', 'hiragana':u'はち', 'romaji':'hachi'},{'word':'eight o\'clock', 'kanji':u'八時', 'hiragana':u'はちじ', 'romaji':'hachiji'},
                    {'word':'eight hundred', 'kanji':u'八百', 'hiragana':u'はっぴゃく', 'romaji':'happyaku'}]},
       {'kanji':u'九', 'eng':'nine', 'romajip':['kyuu','ku'], 'hiraganap':[u'きゅう',u'く'],
            'words':[{'word':'nine', 'kanji':u'九', 'hiragana':u'きゅう', 'romaji':'kyuu'},{'word':'nine o\'clock', 'kanji':u'九時', 'hiragana':u'くじ', 'romaji':'kuji'}]},
       {'kanji':u'十', 'eng':'ten', 'romajip':'juu', 'hiraganap':u'じゅう',
            'words':[{'word':'ten', 'kanji':u'十', 'hiragana':u'じゅう', 'romaji':'juu'},{'word':'ten o\'clock', 'kanji':u'十時', 'hiragana':u'じゅうじ', 'romaji':'juuji'}]},
       {'kanji':u'百', 'eng':'hundred', 'romajip':['hyaku','byaku','pyaku'], 'hiraganap':[u'ひゃく',u'びゃく',u'ぴゃく'],
            'words':[{'word':'hundred', 'kanji':u'百', 'hiragana':u'ひゃく', 'romaji':'hyaku'},{'word':'three hundred', 'kanji':u'三百', 'hiragana':u'さんびゃく', 'romaji':'sanbyaku'},
                    {'word':'six hundred', 'kanji':u'六百', 'hiragana':u'ろっぴゃく', 'romaji':'ropphyaku'},{'word':'eight hundred', 'kanji':u'八百', 'hiragana':u'はっぴゃく', 'romaji':'happyaku'}]},
       {'kanji':u'千', 'eng':'thousand', 'romajip':['sen','zen'], 'hiraganap':[u'せん',u'ぜん'],
            'words':[{'word':'thousand', 'kanji':u'千', 'hiragana':u'せん', 'romaji':'sen'},{'word':'three thousand', 'kanji':u'三千', 'hiragana':u'さんぜん', 'romaji':'sanzen'},
                    {'word':'eight thousand', 'kanji':u'八千', 'hiragana':u'はっせん', 'romaji':'hassen'},{'word':'one thousand yen', 'kanji':u'千円', 'hiragana':u'せんえん', 'romaji':'senen'}]},
       {'kanji':u'万', 'eng':'ten thousand', 'romajip':'man', 'hiraganap':u'まん',
            'words':[{'word':'ten thousand', 'kanji':u'一万', 'hiragana':u'いちまん', 'romaji':'ichiman'},{'word':'one hundred thousand', 'kanji':u'十万', 'hiragana':u'じゅうまん', 'romaji':'juuman'},
                    {'word':'one million', 'kanji':u'百万', 'hiragana':u'ひゃくまん', 'romaji':'hyakuman'}]},
       {'kanji':u'円', 'eng':['yen','circle'], 'romajip':'en', 'hiraganap':u'えん',
            'words':{'word':'one hundred yen', 'kanji':u'百円', 'hiragana':u'ひゃくえん', 'romaji':'hyakuen'}},
       {'kanji':u'時', 'eng':'time', 'romajip':'ji', 'hiraganap':u'じ',
            'words':{'word':'one o\'clock', 'kanji':u'一時', 'hiragana':u'いちじ', 'romaji':'ichiji'}}
       ]
