# encoding: utf-8

ch3V = [{'word':'movie', 'romaji':'eiga', 'kana': u'映画', 'hiragana': u'えいが'},
		{'word':'music', 'romaji':'ongaku', 'kana': u'音楽', 'hiragana': u'おんがく'},
		{'word':'magazine', 'romaji':'zasshi', 'kana': u'雑誌', 'hiragana': u'ざっし'},
		{'word':'sports', 'romaji':'supootsu', 'kana': u'スポツ', 'hiragana': u'スポツ'},
		{'word':'date (romantic)', 'romaji':'deeto', 'kana': u'デート', 'hiragana': u'デート'},
		{'word':'tennis', 'romaji':'tenisu', 'kana': u'テニス', 'hiragana': u'テニス'},
		{'word':'tv', 'romaji':'terebi', 'kana': u'テレビ', 'hiragana': u'テレビ'},
		{'word':'ice cream', 'romaji':'aisukuriimu', 'kana': u'アイスクリーム', 'hiragana': u'アイスクリーム'},
		{'word':'breakfast', 'romaji':'asagohan', 'kana': u'朝ご飯', 'hiragana': u'あさごはん'},
		{'word':['sake', 'alcohol'], 'romaji':'osake', 'kana': u'お酒', 'hiragana': u'おさけ'},
		{'word':'green tea', 'romaji':'ocha', 'kana': u'お茶', 'hiragana': u'おちゃ'},
		{'word':'coffee', 'romaji':'koohii', 'kana': u'コーヒー', 'hiragana': u'コーヒー'},
		{'word':'dinner', 'romaji':'bangohan', 'kana': u'晩ご飯', 'hiragana': u'ばんごはん'},
		{'word':'hamburger', 'romaji':'hanbaagaa', 'kana': u'ハンバーガー', 'hiragana': u'ハンバーガー'},
		{'word':'lunch', 'romaji':'hirugohan', 'kana': u'昼ご飯', 'hiragana': u'ひるごはん'},
		{'word':'water', 'romaji':'mizu', 'kana': u'水', 'hiragana': u'みず'},
		{'word':['home', 'house'], 'romaji':'ie', 'kana': u'家', 'hiragana': u'いえ'},
		{'word':['my home', 'my house', 'my place'], 'romaji':'uchi', 'kana': u'うち', 'hiragana': u'うち'},
		{'word':'school', 'romaji':'gakkou', 'kana': u'学校', 'hiragana': u'がっこう'},
		{'word':'morning', 'romaji':'asa', 'kana': u'朝', 'hiragana': u'あさ'},
        {'word':'tomorrow', 'romaji':'ashita', 'kana': u'明日', 'hiragana': u'あした'},
        {'word':'when', 'romaji':'itsu', 'kana': u'いつ', 'hiragana': u'いつ'},
        {'word':'today', 'romaji':'kyou', 'kana': u'今日', 'hiragana': u'きょう'},
        {'word':'at about~', 'romaji':'~goro', 'kana': u'～ごろ', 'hiragana': u'～ごろ'},
        {'word':'tonight', 'romaji':'konban', 'kana': u'今晩', 'hiragana': u'こんばん'},
        {'word':'weekend', 'romaji':'shuumatsu', 'kana': u'週末', 'hiragana': u'しゅうまつ'},
        {'word':'saturday', 'romaji':'doyoubi', 'kana': u'土曜日', 'hiragana': u'どようび'},
        {'word':'sunday', 'romaji':'nichiyoubi', 'kana': u'日曜日', 'hiragana': u'にちようび'},
        {'word':'every day', 'romaji':'mainichi', 'kana': u'毎日', 'hiragana': u'まいにち'},
        {'word':'every night', 'romaji':'maiban', 'kana': u'毎晩', 'hiragana': u'まいばん'},
        {'word':'to go', 'romaji':'iku', 'kana': u'行く', 'hiragana': u'いく'},
        {'word':['to go back','to return'], 'romaji':'kaeru', 'kana': u'帰る', 'hiragana': u'かえる'},
        {'word':['to listen','to hear'], 'romaji':'kiku', 'kana': u'聞く', 'hiragana': u'きく'},
        {'word':'to drink', 'romaji':'nomu', 'kana': u'飲む', 'hiragana': u'のむ'},
        {'word':['to speak','to talk'], 'romaji':'hanasu', 'kana': u'話す', 'hiragana': u'はなす'},
        {'word':'to read', 'romaji':'yomu', 'kana': u'読む', 'hiragana': u'よむ'},
        {'word':'to get up', 'romaji':'okiru', 'kana': u'起きる', 'hiragana': u'おきる'},
        {'word':'to eat', 'romaji':'taberu', 'kana': u'食べる', 'hiragana': u'たべる'},
        {'word':['to sleep','to go to sleep'], 'romaji':'neru', 'kana': u'寝る', 'hiragana': u'ねる'},
        {'word':['to see','to look at','to watch'], 'romaji':'miru', 'kana': u'見る', 'hiragana': u'みる'},
        {'word':'to come', 'romaji':'kuru', 'kana': u'来る', 'hiragana': u'くる'},
        {'word':'to do', 'romaji':'suru', 'kana': u'する', 'hiragana': u'する'},
        {'word':'to study', 'romaji':'benkyousuru', 'kana': u'勉強する', 'hiragana': u'べんきょうする'},
        {'word':'good', 'romaji':'ii', 'kana': u'いい', 'hiragana': u'いい'},
        {'word':'early', 'romaji':'hayai', 'kana': u'早い', 'hiragana': u'はやい'},
        {'word':'not much', 'romaji':'amari', 'kana': u'あまり', 'hiragana': u'あまり'},
        {'word':'not at all', 'romaji':'zenzen', 'kana': u'全然', 'hiragana': u'ぜんぜん'},
        {'word':'usually', 'romaji':'taitei', 'kana': u'たいてい', 'hiragana': u'たいてい'},
        {'word':'a little', 'romaji':'chotto', 'kana': u'ちょっと', 'hiragana': u'ちょっお'},
        {'word':'sometimes', 'romaji':'tokidoki', 'kana': u'時々', 'hiragana': u'ときどき'},
        {'word':['often','much'], 'romaji':'yoku', 'kana': u'よく', 'hiragana': u'よく'},
        {'word':['that\'s right', 'let me see'], 'romaji':'sou desu ne', 'kana': u'そうですね', 'hiragana': u'そうですね'},
        {'word':'but', 'romaji':'demo', 'kana': u'でも', 'hiragana': u'でも'},
        {'word':['how about~','how is~'], 'romaji':'dou desu  ka', 'kana': u'どうですか', 'hiragana': u'どうですか'}
]
