# encoding: utf-8

ch4V = [{'word':'part-time job', 'romaji':'arubaito', 'kana': u'', 'hiragana': u''},
        {'word':'shopping', 'romaji':'kaimono', 'kana': u'', 'hiragana': u''},
        {'word':'class', 'romaji':'kurasu', 'kana': u'', 'hiragana': u''},
        {'word':'you', 'romaji':'anata', 'kana': u'', 'hiragana': u''},
        {'word':'chair', 'romaji':'isu', 'kana': u'', 'hiragana': u''},
        {'word':'dog', 'romaji':'inu', 'kana': u'', 'hiragana': u''},
        {'word':'souvenir', 'romaji':'omiyage', 'kana': u'', 'hiragana': u''},
        {'word':'child', 'romaji':'kodomo', 'kana': u'', 'hiragana': u''},
        {'word':['rice', 'meal'], 'romaji':'gohan', 'kana': u'', 'hiragana': u''},
        {'word':['picture', 'photograph'], 'romaji':'shashin', 'kana': u'', 'hiragana': u''},
        {'word':'desk', 'romaji':'tsukue', 'kana': u'', 'hiragana': u''},
        {'word':'letter', 'romaji':'tegami', 'kana': u'', 'hiragana': u''},
        {'word':'cat', 'romaji':'neko', 'kana': u'', 'hiragana': u''},
        {'word':'bread', 'romaji':'pan', 'kana': u'', 'hiragana': u''},
        {'word':'person', 'romaji':'hito', 'kana': u'', 'hiragana': u''},
        {'word':'email', 'romaji':'meeru', 'kana': u'', 'hiragana': u''},
        {'word':'temple', 'romaji':'otera', 'kana': u'', 'hiragana': u''},
        {'word':'park', 'romaji':'kouen', 'kana': u'', 'hiragana': u''},
        {'word':'supermarket', 'romaji':'suupaa', 'kana': u'', 'hiragana': u''},
        {'word':'department store', 'romaji':'depaato', 'kana': u'', 'hiragana': u''},
        {'word':'bus stop', 'romaji':'basutei', 'kana': u'', 'hiragana': u''},
        {'word':'hospital', 'romaji':'byouin', 'kana': u'', 'hiragana': u''},
        {'word':'hotel', 'romaji':'hoteru', 'kana': u'', 'hiragana': u''},
        {'word':'bookstore', 'romaji':'honya', 'kana': u'', 'hiragana': u''},
        {'word':['town', 'city'], 'romaji':'machi', 'kana': u'', 'hiragana': u''},
        {'word':'restaurant', 'romaji':'resutoran', 'kana': u'', 'hiragana': u''},
        {'word':'yesterday', 'romaji':'kinou', 'kana': u'', 'hiragana': u''},
        {'word':'~hours', 'romaji':'~jikan', 'kana': u'', 'hiragana': u''},
        {'word':'one hour', 'romaji':'ichijikan', 'kana': u'', 'hiragana': u''},
        {'word':'last week', 'romaji':'senshuu', 'kana': u'', 'hiragana': u''},
        {'word':['when~','at the time of~'], 'romaji':'toki', 'kana': u'', 'hiragana': u''},
        {'word':'monday', 'romaji':'getsuyoubi', 'kana': u'', 'hiragana': u''},
        {'word':'tuesday', 'romaji':'kayoubi', 'kana': u'', 'hiragana': u''},
        {'word':'wednesday', 'romaji':'suiyoubi', 'kana': u'', 'hiragana': u''},
        {'word':'thursday', 'romaji':'mokuyoubi', 'kana': u'', 'hiragana': u''},
        {'word':'friday', 'romaji':'kinyoubi', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''},
        {'word':'', 'romaji':'', 'kana': u'', 'hiragana': u''}
]
